import { Injectable } from '@angular/core';
import { Cafe } from '../../shared/models/Cafe';
import {Tag} from '../../shared/models/Tag';



@Injectable({
  providedIn: 'root'
})
export class CafeService {

  constructor() { }

  getCafeById(id: number): Cafe{
    return this.getAll().find(cafe => cafe.id == id)!;
  }

  getAllTags():Tag[]{
    return[
      {name: 'All', count: 37 },
      {name: 'Cakes', count:8},
      {name: 'Coffee', count: 9},
      {name: 'Drinks', count:10},
      {name: 'Food', count:5},
      {name: 'Ice-Cream', count: 2},
      {name: 'Snacks', count:3},
    ]
  }


  getAllCafesByTag(tag: string): Cafe[]{
    if(tag == "All")
      return this.getAll();
      else
      return this.getAll().filter(cafe => cafe.tags?.includes(tag));

      // return tag "All"?
      // this.getAll()
      // this.getAll().filter(cafe => cafe.tags?.includes(tag));
  }


  getAll():Cafe[]{
    return [

      {
        id: 1,
        name: 'Melting Chocolate Cake',
        price: 4,
        quantity: 12,
        tags: ['Chocolate', 'Melting', 'Cakes'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/cakes/cake1.jpg',
        description: 'A rich and dense chocolate cake flavoured with coffee and vanilla. A chocolate cake that is rich, moist, and delicious.',
        feedback: '',
      },
      {
        id: 2,
        name: 'Caramel Princess',
        price: 6,
        quantity: 16,
        tags: ['Caramel', 'Cakes', 'Princess'],
        favorite: false,
        stars: 5.0,
        imageUrl: '/assets/images/cakes/cake2.jpg',
        description: 'A delicious combination of caramel, cheese and nuts',
        feedback: '',
      },
      {
        id: 3,
        name: 'Taste of Forest',
        price: 4,
        quantity: 22,
        tags: ['Cakes', 'Forest'],
        favorite: false,
        stars: 4.0,
        imageUrl: '/assets/images/cakes/cake3.jpg',
        description: 'The tastes of the forest dances in your mouth - rassberry and vanilla',
        feedback: '',
      },
      {
        id: 4,
        name: 'Easter Cake',
        price: 3,
        quantity: 10,
        tags: ['Cakes', 'Easter'],
        favorite: false,
        stars: 4.8,
        imageUrl: '/assets/images/cakes/cake4.jpg',
        description: 'The perfect cake for Easter with chocolate and vanilla cream',
        feedback: '',
      },
      {
        id: 5,
        name: 'Chocolate Bite',
        price: 2,
        quantity: 5,
        tags: ['Cakes', 'Chocolate'],
        favorite: true,
        stars: 4.5,
        imageUrl: '/assets/images/cakes/cake5.jpg',
        description: 'In this bite is all you need if you are a chocolate lover',
        feedback: '',
      },
      {
        id: 6,
        name: 'Biscuitta',
        price: 4,
        quantity: 19,
        tags: ['Cakes', 'French', 'Biscuits'],
        favorite: false,
        stars: 4.0,
        imageUrl: '/assets/images/cakes/cake6.jpg',
        description: 'The classic French biscuit cake',
        feedback: '',
      },
      {
        id: 7,
        name: 'Pancaky',
        price: 3,
        quantity: 25,
        tags: ['Cakes', 'American','Spanish'],
        favorite: false,
        stars: 4.3,
        imageUrl: '/assets/images/cakes/cake7.jpg',
        description: 'The American pancake made by Spain with wheap cream',
        feedback: '',
      },
      {
        id: 8,
        name: 'Berries Love',
        price: 5,
        quantity: 11,
        tags: ['Cakes', 'Berries'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/cakes/cake8.jpg',
        description: 'Berries, fruits and cream - it feels like a hug',
        feedback: '',
      },
      {
        id: 9,
        name: 'Esspreso',
        price: 4,
        quantity: 30,
        tags: ['Coffee', 'Esspreso'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/coffee/coffee1.jpg',
        description: 'The good taste of the Arabian coffee',
        feedback: '',
      },
      {
        id: 10,
        name: 'Chocolate Milkshake',
        price: 4,
        quantity: 15,
        tags: ['Coffee'],
        favorite: false,
        stars: 4.7,
        imageUrl: '/assets/images/coffee/coffee2.jpg',
        description: 'Your classic chocolate sweet milkshake',
        feedback: '',
      },
      {
        id: 11,
        name: 'Caramel Frappucino',
        price: 3,
        quantity: 4,
        tags: ['Coffee', 'Frappucino', 'Caramel'],
        favorite: true,
        stars: 4.4,
        imageUrl: '/assets/images/coffee/coffee3.jpg',
        description: 'Extra caramel in your day',
        feedback: '',
      },
      {
        id: 12,
        name: 'Latte Machiatto',
        price: 4,
        quantity: 8,
        tags: ['Coffee','Latte','Machiatto'],
        favorite: false,
        stars: 5.0,
        imageUrl: '/assets/images/coffee/coffee4.jpg',
        description: 'It is an example of a latte coffee art',
        feedback: '',
      },
      {
        id: 13,
        name: 'Ice Frappucino',
        price: 5,
        quantity: 20,
        tags: ['Coffee', 'Ice', 'Frappucino'],
        favorite: true,
        stars: 4.8,
        imageUrl: '/assets/images/coffee/coffeen6.jpg',
        description: 'It goes perfect on the summer',
        feedback: '',
      },
      {
        id: 14,
        name: 'Mango Ice Coffee',
        price: 3,
        quantity: 6,
        tags: ['Coffee'],
        favorite: false,
        stars: 4.3,
        imageUrl: '/assets/images/coffee/coffeen3.jpg',
        description: 'The taste of mango will make your day',
        feedback: '',
      },
      {
        id: 15,
        name: 'Chocolate Coffee',
        price: 4,
        quantity: 10,
        tags: ['Coffee', 'Chocolate'],
        favorite: true,
        stars: 4.5,
        imageUrl: '/assets/images/coffee/coffeen4.jpg',
        description: 'For the coffee and chocolate lovers',
        feedback: '',
      },
      {
        id: 16,
        name: 'Cappucino',
        price: 3,
        quantity: 25,
        tags: ['Coffee','Cappucino'],
        favorite: true,
        stars: 4.0,
        imageUrl: '/assets/images/coffee/coffeen1.png',
        description: 'The classic cappucino',
        feedback: '',
      },
      {
        id: 17,
        name: 'Caramel Cappucino',
        price: 3,
        quantity: 14,
        tags: ['Coffee','Caramel','Cappucino'],
        favorite: false,
        stars: 4.0,
        imageUrl: '/assets/images/coffee/coffeen5.png',
        description: 'Caramel lovers but also cappucino needers',
        feedback: '',
      },
      {
        id: 18,
        name: 'Mint Lemonade',
        price: 6,
        quantity: 14,
        tags: ['Drinks','Mint'],
        favorite: false,
        stars: 4.3,
        imageUrl: '/assets/images/drinks/drink1.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 19,
        name: 'Fruit Smoothie ',
        price: 2,
        quantity: 12,
        tags: ['Drinks'],
        favorite: true,
        stars: 4.8,
        imageUrl: '/assets/images/drinks/drink2.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 20,
        name: 'Kiwi Smoothie',
        price: 2,
        quantity: 6,
        tags: ['Drinks'],
        favorite: false,
        stars: 5.0,
        imageUrl: '/assets/images/drinks/drink3.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 21,
        name: 'Dragon Fruit Smoothie',
        price: 3,
        quantity: 22,
        tags: ['Drinks'],
        favorite: true,
        stars: 4.1,
        imageUrl: '/assets/images/drinks/drink4.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 22,
        name: 'Rosy',
        price: 4,
        quantity: 1,
        tags: ['Drinks'],
        favorite: false,
        stars: 4.9,
        imageUrl: '/assets/images/drinks/drink5.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 23,
        name: 'Ice Tea',
        price: 3,
        quantity: 18,
        tags: ['Drinks'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/drinks/drink6.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 24,
        name: 'Orange Lemonade',
        price: 4,
        quantity: 4,
        tags: ['Drinks'],
        favorite: true,
        stars: 4.7,
        imageUrl: '/assets/images/drinks/drink7.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 25,
        name: 'Red Lemonade',
        price: 5,
        quantity: 2,
        tags: ['Drinks'],
        favorite: false,
        stars: 5.0,
        imageUrl: '/assets/images/drinks/drink8.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 26,
        name: 'Ice Lemon Lemonade',
        price: 2,
        quantity: 2,
        tags: ['Drinks'],
        favorite: true,
        stars: 4.8,
        imageUrl: '/assets/images/drinks/drink9.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 27,
        name: 'Water',
        price: 1,
        quantity: 50,
        tags: ['Drinks'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/drinks/drink10.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 28,
        name: 'Ham Sandwich',
        price: 5,
        quantity: 11,
        tags: ['Food'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/food/food1.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 29,
        name: 'Avocado Egg Sandwich',
        price: 4,
        quantity: 14,
        tags: ['Food'],
        favorite: false,
        stars: 4.1,
        imageUrl: '/assets/images/food/food2.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 30,
        name: 'Chicken Sandwich',
        price: 4,
        quantity: 2,
        tags: ['Food'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/food/food3.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 31,
        name: 'Salami Sandwich',
        price: 4,
        quantity: 12,
        tags: ['Food'],
        favorite: true,
        stars: 4.6,
        imageUrl: '/assets/images/food/food4.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 32,
        name: 'Salad',
        price: 4,
        quantity: 7,
        tags: ['Food'],
        favorite: true,
        stars: 4.5,
        imageUrl: '/assets/images/food/food5.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 33,
        name: 'Berries Chocolate Ice Cream',
        price: 5,
        quantity: 17,
        tags: ['Ice-Cream'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/ice-cream/icecream1.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 34,
        name: 'Salty Ice Cream',
        price: 5,
        quantity: 10,
        tags: ['Ice-Cream'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/ice-cream/icecream2.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 35,
        name: 'American Pancakes',
        price: 6,
        quantity: 5,
        tags: ['Snacks'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/snacks/snack1.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 36,
        name: 'Churros',
        price: 4,
        quantity: 22,
        tags: ['Snacks'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/snacks/snack2.jpg',
        description: '',
        feedback: '',
      },
      {
        id: 37,
        name: 'Croissant',
        price: 3,
        quantity: 6,
        tags: ['Snacks'],
        favorite: true,
        stars: 5.0,
        imageUrl: '/assets/images/snacks/snack3.jpg',
        description: '',
        feedback: '',
      },



      // '/assets/images/cakes/cake1.jpg',
      // '/assets/images/cakes/cake2.jpg',
      // '/assets/images/cakes/cake3.jpg',
      // '/assets/images/cakes/cake4.jpg',
      // '/assets/images/cakes/cake5.jpg',
      // '/assets/images/cakes/cake6.jpg',
      // '/assets/images/cakes/cake7.jpg',
      // '/assets/images/cakes/cake8.jpg',
      // '/assets/images/coffee/coffee1.jpg',
      // '/assets/images/coffee/coffee2.jpg',
      // '/assets/images/coffee/coffee3.jpg',
      // '/assets/images/coffee/coffee4.jpg',
      // '/assets/images/coffee/coffee5.jpg',
      // '/assets/images/coffee/coffee6.jpg',
      // '/assets/images/coffee/coffee7.jpg',
      // '/assets/images/coffee/coffee8.jpg',
      // '/assets/images/coffee/coffee9.jpg',
      // '/assets/images/drinks/drink1.jpg',
      // '/assets/images/drinks/drink2.jpg',
      // '/assets/images/drinks/drink3.jpg',
      // '/assets/images/drinks/drink4.jpg',
      // '/assets/images/drinks/drink5.jpg',
      // '/assets/images/drinks/drink6.jpg',
      // '/assets/images/drinks/drink7.jpg',
      // '/assets/images/drinks/drink8.jpg',
      // '/assets/images/drinks/drink9.jpg',
      // '/assets/images/drinks/drink10.jpg',
      // '/assets/images/food/food1.jpg',
      // '/assets/images/food/food2.jpg',
      // '/assets/images/food/food3.jpg',
      // '/assets/images/food/food4.jpg',
      // '/assets/images/food/food5.jpg',
      // '/assets/images/ice-cream/icecream1.jpg',
      // '/assets/images/ice-cream/icecream2.jpg',
      // '/assets/images/snacks/snack1.jpg',
      // '/assets/images/snacks/snack2.jpg',
      // '/assets/images/snacks/snack3.jpg',

    ]
  }

}
